import { APP_NAME, APP_TAGLINE, PolicySection, PolicyTrustCard } from './policy-catalog';

export const TERMS_VERSION = '2.0';
export const TERMS_UPDATED_AT = 'August 2026';
export const TERMS_CONTACT_EMAIL = 'legal@lexora.app';
export const TERMS_CONTACT_ADDRESS = 'Gurgaon, Haryana, India';

export interface TermsDocument {
  title: string;
  badge: string;
  description: string;
  updatedAt: string;
  version: string;
  overviewTitle: string;
  overviewDescription: string;
  noticeText: string;
  trustCards: PolicyTrustCard[];
  sections: PolicySection[];
  contactEmail: string;
  contactAddress: string;
}

export const TERMS_OF_SERVICE: TermsDocument = {
  title: 'Terms of Service',
  badge: 'Legal Agreement',
  description: `These Terms of Service govern access to and use of ${APP_NAME}, the ${APP_TAGLINE} for multi-tenant institutions, branches, libraries, members, attendance, books, billing, analytics, and administration.`,
  updatedAt: TERMS_UPDATED_AT,
  version: TERMS_VERSION,
  overviewTitle: 'Legal Overview',
  overviewDescription:
    'This agreement defines your rights, institutional responsibilities, subscription terms, acceptable use requirements, data ownership, and service limitations while using the platform.',
  noticeText: `By accessing or using ${APP_NAME}, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service and the policies referenced below, including the Privacy Policy and Data Processing terms.`,
  trustCards: [
    {
      icon: 'building-2',
      title: 'Institution First',
      description: 'Institutions control their tenant data, members, and operational records.',
    },
    {
      icon: 'shield-check',
      title: 'Secure Access',
      description: 'Role-based permissions scope staff to authorized institutions, branches, and libraries.',
    },
    {
      icon: 'credit-card',
      title: 'Clear Billing',
      description: 'Subscription packages, trials, and renewals are described before purchase.',
    },
    {
      icon: 'life-buoy',
      title: 'Support Available',
      description: 'Help is available for onboarding, billing questions, and platform issues.',
    },
  ],
  sections: [
    {
      id: 'introduction',
      title: 'Introduction',
      icon: 'book-open',
      kind: 'paragraph',
      paragraphs: [
        `Welcome to ${APP_NAME}. These Terms of Service ("Terms") govern your use of our website, web application, APIs, attendance kiosk endpoints, and related services (collectively, the "Service").`,
        'If you register on behalf of an institution, you represent that you have authority to bind that institution to these Terms. If you do not agree, you must not use the Service.',
      ],
    },
    {
      id: 'definitions',
      title: 'Definitions',
      icon: 'file-text',
      kind: 'cards',
      cards: [
        {
          title: 'Service',
          body: `The ${APP_NAME} platform, including dashboards, admin tools, member workflows, and integrations.`,
        },
        {
          title: 'Institution',
          body: 'The top-level tenant organisation that owns branches, libraries, and member records.',
        },
        {
          title: 'Administrator',
          body: 'A staff user authorized to configure institutions, roles, billing, and operational settings.',
        },
        {
          title: 'Member',
          body: 'An individual registered under an institution and mapped to a library for plans and attendance.',
        },
        {
          title: 'Subscription',
          body: 'A paid or trial package granting access to platform features for a defined billing period.',
        },
        {
          title: 'Customer Data',
          body: 'Records uploaded or generated by an institution, including members, attendance, books, and billing data.',
        },
      ],
    },
    {
      id: 'registration',
      title: 'Account Registration & Eligibility',
      icon: 'user-plus',
      kind: 'list',
      items: [
        'Provide accurate institution, branch, and administrator information during onboarding.',
        'Maintain the confidentiality of passwords, OTP credentials, and API tokens.',
        'Ensure only authorized personnel receive administrative access.',
        'Notify us promptly of suspected unauthorized access or security incidents.',
        'Do not create accounts for unlawful purposes or impersonate another party.',
      ],
    },
    {
      id: 'multi-tenant',
      title: 'Multi-Tenant Structure & Responsibilities',
      icon: 'layers',
      kind: 'paragraph',
      paragraphs: [
        `${APP_NAME} uses a multi-tenant architecture: Institution → Branch → Library → Member. Institutions are responsible for configuring their hierarchy, assigning staff roles, and ensuring member data is collected and used lawfully.`,
        'Each member is mapped to one library. Attendance, plans, and operational records are scoped accordingly. Institutions must not attempt to access another tenant\'s data.',
      ],
    },
    {
      id: 'acceptable-use',
      title: 'Acceptable Use',
      icon: 'shield',
      kind: 'list',
      items: [
        'Use the Service only for legitimate library and institutional operations.',
        'Do not interfere with platform security, availability, or other tenants.',
        'Do not scrape, reverse engineer, or bypass access controls.',
        'Do not share credentials or export member data beyond authorized purposes.',
        'Do not misuse QR codes, attendance kiosks, or scanner endpoints.',
        'See the full Acceptable Use Policy for additional restrictions.',
      ],
    },
    {
      id: 'data',
      title: 'Data Ownership & Processing',
      icon: 'database',
      kind: 'highlight',
      paragraphs: [
        `Institutions retain ownership of Customer Data stored in ${APP_NAME}. We process Customer Data only to provide and improve the Service, support institutions, maintain security, and comply with law.`,
        `${APP_NAME} does not claim ownership of institution records. Institutions are responsible for obtaining lawful basis and consent when collecting member personal data. Our Privacy Policy and Data Processing Agreement describe processing in more detail.`,
      ],
    },
    {
      id: 'subscriptions',
      title: 'Subscriptions, Billing & Trials',
      icon: 'credit-card',
      kind: 'list',
      items: [
        'Free, trial, and paid packages may be offered with different feature limits.',
        'Fees are billed according to the selected package and billing cycle shown at purchase.',
        'Trials convert to paid plans or eligible free tiers when the trial period ends unless cancelled.',
        'Pricing and included features may change with reasonable notice for future billing periods.',
        'Refund and billing disputes are handled under the Refund & Billing Policy.',
      ],
    },
    {
      id: 'availability',
      title: 'Service Availability & Support',
      icon: 'life-buoy',
      kind: 'paragraph',
      paragraphs: [
        'We aim to provide reliable access to the Service but do not guarantee uninterrupted availability. Maintenance, updates, or events outside our control may cause temporary downtime.',
        'Support channels and response targets may vary by subscription plan. Institutions should use in-app support for operational and billing assistance.',
      ],
    },
    {
      id: 'ip',
      title: 'Intellectual Property',
      icon: 'sparkles',
      kind: 'paragraph',
      paragraphs: [
        `${APP_NAME}, its software, branding, documentation, and underlying technology are owned by us or our licensors. These Terms do not grant ownership of the Service—only a limited, non-exclusive, non-transferable right to use it during an active subscription.`,
      ],
    },
    {
      id: 'liability',
      title: 'Disclaimer & Limitation of Liability',
      icon: 'triangle-alert',
      kind: 'paragraph',
      paragraphs: [
        'The Service is provided on an "as is" and "as available" basis to the maximum extent permitted by law. We disclaim warranties of merchantability, fitness for a particular purpose, and non-infringement where allowed.',
        'To the extent permitted by law, we are not liable for indirect, incidental, special, consequential, or punitive damages, or for loss of profits, data, or business opportunity arising from use of the Service.',
      ],
    },
    {
      id: 'termination',
      title: 'Suspension & Termination',
      icon: 'power',
      kind: 'list',
      items: [
        'Institutions may cancel subscriptions according to plan terms and billing settings.',
        'We may suspend or terminate access for material breach, non-payment, abuse, or legal requirement.',
        'Upon termination, access to the Service may end and data may be deleted after any applicable retention period.',
        'Provisions that by nature should survive termination will remain in effect.',
      ],
    },
    {
      id: 'changes',
      title: 'Changes to These Terms',
      icon: 'refresh-cw',
      kind: 'paragraph',
      paragraphs: [
        'We may update these Terms from time to time. Material changes will be communicated through the Service, email, or the policies hub. Continued use after the effective date constitutes acceptance of the updated Terms.',
      ],
    },
    {
      id: 'law',
      title: 'Governing Law',
      icon: 'badge-check',
      kind: 'paragraph',
      paragraphs: [
        'These Terms are governed by the laws of India, without regard to conflict-of-law principles. Courts in Gurgaon, Haryana shall have exclusive jurisdiction, subject to mandatory consumer protections where applicable.',
      ],
    },
  ],
  contactEmail: TERMS_CONTACT_EMAIL,
  contactAddress: TERMS_CONTACT_ADDRESS,
};

export const RELATED_POLICY_LINKS = [
  { route: '/policies', title: 'All Policies', description: 'Complete policy library' },
  { route: '/privacy-policy', title: 'Privacy Policy', description: 'How we handle personal data' },
  { route: '/data-processing', title: 'Data Processing', description: 'Institutional processing terms' },
  { route: '/acceptable-use', title: 'Acceptable Use', description: 'Platform usage rules' },
  { route: '/security-policy', title: 'Security Policy', description: 'Security controls overview' },
  { route: '/refund-policy', title: 'Refund & Billing', description: 'Subscriptions and refunds' },
] as const;
