/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingLibraryRouteImport } from './routes/onboarding.library'
import { Route as OnboardingInstitutionRouteImport } from './routes/onboarding.institution'
import { Route as OnboardingBranchRouteImport } from './routes/onboarding.branch'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSeatsRouteImport } from './routes/_authenticated.seats'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated.attendance'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated._admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated.teachers.index'
import { Route as AuthenticatedSupportIndexRouteImport } from './routes/_authenticated.support.index'
import { Route as AuthenticatedSubscriptionsIndexRouteImport } from './routes/_authenticated.subscriptions.index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated.students.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedSeatsIndexRouteImport } from './routes/_authenticated.seats.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated.reports.index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated.payments.index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated.notifications.index'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated.members.index'
import { Route as AuthenticatedLibrariesIndexRouteImport } from './routes/_authenticated.libraries.index'
import { Route as AuthenticatedInstitutionsIndexRouteImport } from './routes/_authenticated.institutions.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedBranchesIndexRouteImport } from './routes/_authenticated.branches.index'
import { Route as AuthenticatedBooksIndexRouteImport } from './routes/_authenticated.books.index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated.attendance.index'
import { Route as AuthenticatedTeachersCreateRouteImport } from './routes/_authenticated.teachers.create'
import { Route as AuthenticatedTeachersTeacherIdRouteImport } from './routes/_authenticated.teachers.$teacherId'
import { Route as AuthenticatedSupportStatusRouteImport } from './routes/_authenticated.support.status'
import { Route as AuthenticatedStudentsCreateRouteImport } from './routes/_authenticated.students.create'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated.students.$studentId'
import { Route as AuthenticatedSettingsThemeRouteImport } from './routes/_authenticated.settings.theme'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated.settings.security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated.settings.profile'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated.settings.notifications'
import { Route as AuthenticatedSettingsInstitutionRouteImport } from './routes/_authenticated.settings.institution'
import { Route as AuthenticatedSettingsBrandingRouteImport } from './routes/_authenticated.settings.branding'
import { Route as AuthenticatedSettingsAuditRouteImport } from './routes/_authenticated.settings.audit'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated.settings.api-keys'
import { Route as AuthenticatedSeatsMonitoringRouteImport } from './routes/_authenticated.seats.monitoring'
import { Route as AuthenticatedSeatsLayoutRouteImport } from './routes/_authenticated.seats.layout'
import { Route as AuthenticatedSeatsHeatmapRouteImport } from './routes/_authenticated.seats.heatmap'
import { Route as AuthenticatedMembersCreateRouteImport } from './routes/_authenticated.members.create'
import { Route as AuthenticatedMembersMemberIdRouteImport } from './routes/_authenticated.members.$memberId'
import { Route as AuthenticatedLibrariesCreateRouteImport } from './routes/_authenticated.libraries.create'
import { Route as AuthenticatedLibrariesLibraryIdRouteImport } from './routes/_authenticated.libraries.$libraryId'
import { Route as AuthenticatedInstitutionsCreateRouteImport } from './routes/_authenticated.institutions.create'
import { Route as AuthenticatedInstitutionsInstitutionIdRouteImport } from './routes/_authenticated.institutions.$institutionId'
import { Route as AuthenticatedDashboardSubscriptionsRouteImport } from './routes/_authenticated.dashboard.subscriptions'
import { Route as AuthenticatedDashboardRevenueRouteImport } from './routes/_authenticated.dashboard.revenue'
import { Route as AuthenticatedDashboardOccupancyRouteImport } from './routes/_authenticated.dashboard.occupancy'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated.dashboard.notifications'
import { Route as AuthenticatedDashboardAttendanceRouteImport } from './routes/_authenticated.dashboard.attendance'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated.dashboard.analytics'
import { Route as AuthenticatedDashboardActivityRouteImport } from './routes/_authenticated.dashboard.activity'
import { Route as AuthenticatedBranchesCreateRouteImport } from './routes/_authenticated.branches.create'
import { Route as AuthenticatedBranchesBranchIdRouteImport } from './routes/_authenticated.branches.$branchId'
import { Route as AuthenticatedAttendanceShiftsRouteImport } from './routes/_authenticated.attendance.shifts'
import { Route as AuthenticatedAttendanceScannerRouteImport } from './routes/_authenticated.attendance.scanner'
import { Route as AuthenticatedAttendanceLiveRouteImport } from './routes/_authenticated.attendance.live'
import { Route as AuthenticatedAttendanceCalendarRouteImport } from './routes/_authenticated.attendance.calendar'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated._admin.users.index'
import { Route as AuthenticatedAdminRolesIndexRouteImport } from './routes/_authenticated._admin.roles.index'
import { Route as AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRouteImport } from './routes/_authenticated.institutions.$institutionId.branches.$branchId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLibraryRoute = OnboardingLibraryRouteImport.update({
  id: '/onboarding/library',
  path: '/onboarding/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInstitutionRoute = OnboardingInstitutionRouteImport.update({
  id: '/onboarding/institution',
  path: '/onboarding/institution',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBranchRoute = OnboardingBranchRouteImport.update({
  id: '/onboarding/branch',
  path: '/onboarding/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeatsRoute = AuthenticatedSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportIndexRoute =
  AuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubscriptionsIndexRoute =
  AuthenticatedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSeatsIndexRoute = AuthenticatedSeatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSeatsRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibrariesIndexRoute =
  AuthenticatedLibrariesIndexRouteImport.update({
    id: '/libraries/',
    path: '/libraries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstitutionsIndexRoute =
  AuthenticatedInstitutionsIndexRouteImport.update({
    id: '/institutions/',
    path: '/institutions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedBranchesIndexRoute =
  AuthenticatedBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBooksIndexRoute = AuthenticatedBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedTeachersCreateRoute =
  AuthenticatedTeachersCreateRouteImport.update({
    id: '/teachers/create',
    path: '/teachers/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeachersTeacherIdRoute =
  AuthenticatedTeachersTeacherIdRouteImport.update({
    id: '/teachers/$teacherId',
    path: '/teachers/$teacherId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportStatusRoute =
  AuthenticatedSupportStatusRouteImport.update({
    id: '/support/status',
    path: '/support/status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsCreateRoute =
  AuthenticatedStudentsCreateRouteImport.update({
    id: '/students/create',
    path: '/students/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsThemeRoute =
  AuthenticatedSettingsThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsInstitutionRoute =
  AuthenticatedSettingsInstitutionRouteImport.update({
    id: '/institution',
    path: '/institution',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBrandingRoute =
  AuthenticatedSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAuditRoute =
  AuthenticatedSettingsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSeatsMonitoringRoute =
  AuthenticatedSeatsMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedSeatsRoute,
  } as any)
const AuthenticatedSeatsLayoutRoute =
  AuthenticatedSeatsLayoutRouteImport.update({
    id: '/layout',
    path: '/layout',
    getParentRoute: () => AuthenticatedSeatsRoute,
  } as any)
const AuthenticatedSeatsHeatmapRoute =
  AuthenticatedSeatsHeatmapRouteImport.update({
    id: '/heatmap',
    path: '/heatmap',
    getParentRoute: () => AuthenticatedSeatsRoute,
  } as any)
const AuthenticatedMembersCreateRoute =
  AuthenticatedMembersCreateRouteImport.update({
    id: '/members/create',
    path: '/members/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembersMemberIdRoute =
  AuthenticatedMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibrariesCreateRoute =
  AuthenticatedLibrariesCreateRouteImport.update({
    id: '/libraries/create',
    path: '/libraries/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdRoute =
  AuthenticatedLibrariesLibraryIdRouteImport.update({
    id: '/libraries/$libraryId',
    path: '/libraries/$libraryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstitutionsCreateRoute =
  AuthenticatedInstitutionsCreateRouteImport.update({
    id: '/institutions/create',
    path: '/institutions/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstitutionsInstitutionIdRoute =
  AuthenticatedInstitutionsInstitutionIdRouteImport.update({
    id: '/institutions/$institutionId',
    path: '/institutions/$institutionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSubscriptionsRoute =
  AuthenticatedDashboardSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRevenueRoute =
  AuthenticatedDashboardRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOccupancyRoute =
  AuthenticatedDashboardOccupancyRouteImport.update({
    id: '/occupancy',
    path: '/occupancy',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAttendanceRoute =
  AuthenticatedDashboardAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardActivityRoute =
  AuthenticatedDashboardActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedBranchesCreateRoute =
  AuthenticatedBranchesCreateRouteImport.update({
    id: '/branches/create',
    path: '/branches/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBranchesBranchIdRoute =
  AuthenticatedBranchesBranchIdRouteImport.update({
    id: '/branches/$branchId',
    path: '/branches/$branchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceShiftsRoute =
  AuthenticatedAttendanceShiftsRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceScannerRoute =
  AuthenticatedAttendanceScannerRouteImport.update({
    id: '/scanner',
    path: '/scanner',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceLiveRoute =
  AuthenticatedAttendanceLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceCalendarRoute =
  AuthenticatedAttendanceCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRoute =
  AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRouteImport.update({
    id: '/branches/$branchId',
    path: '/branches/$branchId',
    getParentRoute: () => AuthenticatedInstitutionsInstitutionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/seats': typeof AuthenticatedSeatsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/onboarding/branch': typeof OnboardingBranchRoute
  '/onboarding/institution': typeof OnboardingInstitutionRoute
  '/onboarding/library': typeof OnboardingLibraryRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/attendance/calendar': typeof AuthenticatedAttendanceCalendarRoute
  '/attendance/live': typeof AuthenticatedAttendanceLiveRoute
  '/attendance/scanner': typeof AuthenticatedAttendanceScannerRoute
  '/attendance/shifts': typeof AuthenticatedAttendanceShiftsRoute
  '/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/branches/create': typeof AuthenticatedBranchesCreateRoute
  '/dashboard/activity': typeof AuthenticatedDashboardActivityRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/occupancy': typeof AuthenticatedDashboardOccupancyRoute
  '/dashboard/revenue': typeof AuthenticatedDashboardRevenueRoute
  '/dashboard/subscriptions': typeof AuthenticatedDashboardSubscriptionsRoute
  '/institutions/$institutionId': typeof AuthenticatedInstitutionsInstitutionIdRouteWithChildren
  '/institutions/create': typeof AuthenticatedInstitutionsCreateRoute
  '/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRoute
  '/libraries/create': typeof AuthenticatedLibrariesCreateRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/members/create': typeof AuthenticatedMembersCreateRoute
  '/seats/heatmap': typeof AuthenticatedSeatsHeatmapRoute
  '/seats/layout': typeof AuthenticatedSeatsLayoutRoute
  '/seats/monitoring': typeof AuthenticatedSeatsMonitoringRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/settings/institution': typeof AuthenticatedSettingsInstitutionRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/theme': typeof AuthenticatedSettingsThemeRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/create': typeof AuthenticatedStudentsCreateRoute
  '/support/status': typeof AuthenticatedSupportStatusRoute
  '/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/teachers/create': typeof AuthenticatedTeachersCreateRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/books/': typeof AuthenticatedBooksIndexRoute
  '/branches/': typeof AuthenticatedBranchesIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/institutions/': typeof AuthenticatedInstitutionsIndexRoute
  '/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/seats/': typeof AuthenticatedSeatsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/subscriptions/': typeof AuthenticatedSubscriptionsIndexRoute
  '/support/': typeof AuthenticatedSupportIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/institutions/$institutionId/branches/$branchId': typeof AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/onboarding/branch': typeof OnboardingBranchRoute
  '/onboarding/institution': typeof OnboardingInstitutionRoute
  '/onboarding/library': typeof OnboardingLibraryRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/attendance/calendar': typeof AuthenticatedAttendanceCalendarRoute
  '/attendance/live': typeof AuthenticatedAttendanceLiveRoute
  '/attendance/scanner': typeof AuthenticatedAttendanceScannerRoute
  '/attendance/shifts': typeof AuthenticatedAttendanceShiftsRoute
  '/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/branches/create': typeof AuthenticatedBranchesCreateRoute
  '/dashboard/activity': typeof AuthenticatedDashboardActivityRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/occupancy': typeof AuthenticatedDashboardOccupancyRoute
  '/dashboard/revenue': typeof AuthenticatedDashboardRevenueRoute
  '/dashboard/subscriptions': typeof AuthenticatedDashboardSubscriptionsRoute
  '/institutions/$institutionId': typeof AuthenticatedInstitutionsInstitutionIdRouteWithChildren
  '/institutions/create': typeof AuthenticatedInstitutionsCreateRoute
  '/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRoute
  '/libraries/create': typeof AuthenticatedLibrariesCreateRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/members/create': typeof AuthenticatedMembersCreateRoute
  '/seats/heatmap': typeof AuthenticatedSeatsHeatmapRoute
  '/seats/layout': typeof AuthenticatedSeatsLayoutRoute
  '/seats/monitoring': typeof AuthenticatedSeatsMonitoringRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/settings/institution': typeof AuthenticatedSettingsInstitutionRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/theme': typeof AuthenticatedSettingsThemeRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/create': typeof AuthenticatedStudentsCreateRoute
  '/support/status': typeof AuthenticatedSupportStatusRoute
  '/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/teachers/create': typeof AuthenticatedTeachersCreateRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/books': typeof AuthenticatedBooksIndexRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/institutions': typeof AuthenticatedInstitutionsIndexRoute
  '/libraries': typeof AuthenticatedLibrariesIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/seats': typeof AuthenticatedSeatsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsIndexRoute
  '/support': typeof AuthenticatedSupportIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/users': typeof AuthenticatedAdminUsersIndexRoute
  '/institutions/$institutionId/branches/$branchId': typeof AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/seats': typeof AuthenticatedSeatsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/onboarding/branch': typeof OnboardingBranchRoute
  '/onboarding/institution': typeof OnboardingInstitutionRoute
  '/onboarding/library': typeof OnboardingLibraryRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/attendance/calendar': typeof AuthenticatedAttendanceCalendarRoute
  '/_authenticated/attendance/live': typeof AuthenticatedAttendanceLiveRoute
  '/_authenticated/attendance/scanner': typeof AuthenticatedAttendanceScannerRoute
  '/_authenticated/attendance/shifts': typeof AuthenticatedAttendanceShiftsRoute
  '/_authenticated/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/_authenticated/branches/create': typeof AuthenticatedBranchesCreateRoute
  '/_authenticated/dashboard/activity': typeof AuthenticatedDashboardActivityRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/occupancy': typeof AuthenticatedDashboardOccupancyRoute
  '/_authenticated/dashboard/revenue': typeof AuthenticatedDashboardRevenueRoute
  '/_authenticated/dashboard/subscriptions': typeof AuthenticatedDashboardSubscriptionsRoute
  '/_authenticated/institutions/$institutionId': typeof AuthenticatedInstitutionsInstitutionIdRouteWithChildren
  '/_authenticated/institutions/create': typeof AuthenticatedInstitutionsCreateRoute
  '/_authenticated/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRoute
  '/_authenticated/libraries/create': typeof AuthenticatedLibrariesCreateRoute
  '/_authenticated/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/_authenticated/members/create': typeof AuthenticatedMembersCreateRoute
  '/_authenticated/seats/heatmap': typeof AuthenticatedSeatsHeatmapRoute
  '/_authenticated/seats/layout': typeof AuthenticatedSeatsLayoutRoute
  '/_authenticated/seats/monitoring': typeof AuthenticatedSeatsMonitoringRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/_authenticated/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/_authenticated/settings/institution': typeof AuthenticatedSettingsInstitutionRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/theme': typeof AuthenticatedSettingsThemeRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/students/create': typeof AuthenticatedStudentsCreateRoute
  '/_authenticated/support/status': typeof AuthenticatedSupportStatusRoute
  '/_authenticated/teachers/$teacherId': typeof AuthenticatedTeachersTeacherIdRoute
  '/_authenticated/teachers/create': typeof AuthenticatedTeachersCreateRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/books/': typeof AuthenticatedBooksIndexRoute
  '/_authenticated/branches/': typeof AuthenticatedBranchesIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/institutions/': typeof AuthenticatedInstitutionsIndexRoute
  '/_authenticated/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/seats/': typeof AuthenticatedSeatsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/subscriptions/': typeof AuthenticatedSubscriptionsIndexRoute
  '/_authenticated/support/': typeof AuthenticatedSupportIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/_admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/_admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/institutions/$institutionId/branches/$branchId': typeof AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/register'
    | '/reset-password'
    | '/unauthorized'
    | '/verify-otp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/attendance'
    | '/dashboard'
    | '/seats'
    | '/settings'
    | '/onboarding/branch'
    | '/onboarding/institution'
    | '/onboarding/library'
    | '/.mcp/invoke-tool/$tool'
    | '/attendance/calendar'
    | '/attendance/live'
    | '/attendance/scanner'
    | '/attendance/shifts'
    | '/branches/$branchId'
    | '/branches/create'
    | '/dashboard/activity'
    | '/dashboard/analytics'
    | '/dashboard/attendance'
    | '/dashboard/notifications'
    | '/dashboard/occupancy'
    | '/dashboard/revenue'
    | '/dashboard/subscriptions'
    | '/institutions/$institutionId'
    | '/institutions/create'
    | '/libraries/$libraryId'
    | '/libraries/create'
    | '/members/$memberId'
    | '/members/create'
    | '/seats/heatmap'
    | '/seats/layout'
    | '/seats/monitoring'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/branding'
    | '/settings/institution'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/theme'
    | '/students/$studentId'
    | '/students/create'
    | '/support/status'
    | '/teachers/$teacherId'
    | '/teachers/create'
    | '/attendance/'
    | '/books/'
    | '/branches/'
    | '/dashboard/'
    | '/institutions/'
    | '/libraries/'
    | '/members/'
    | '/notifications/'
    | '/payments/'
    | '/reports/'
    | '/seats/'
    | '/settings/'
    | '/students/'
    | '/subscriptions/'
    | '/support/'
    | '/teachers/'
    | '/roles/'
    | '/users/'
    | '/institutions/$institutionId/branches/$branchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/register'
    | '/reset-password'
    | '/unauthorized'
    | '/verify-otp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/onboarding/branch'
    | '/onboarding/institution'
    | '/onboarding/library'
    | '/.mcp/invoke-tool/$tool'
    | '/attendance/calendar'
    | '/attendance/live'
    | '/attendance/scanner'
    | '/attendance/shifts'
    | '/branches/$branchId'
    | '/branches/create'
    | '/dashboard/activity'
    | '/dashboard/analytics'
    | '/dashboard/attendance'
    | '/dashboard/notifications'
    | '/dashboard/occupancy'
    | '/dashboard/revenue'
    | '/dashboard/subscriptions'
    | '/institutions/$institutionId'
    | '/institutions/create'
    | '/libraries/$libraryId'
    | '/libraries/create'
    | '/members/$memberId'
    | '/members/create'
    | '/seats/heatmap'
    | '/seats/layout'
    | '/seats/monitoring'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/branding'
    | '/settings/institution'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/theme'
    | '/students/$studentId'
    | '/students/create'
    | '/support/status'
    | '/teachers/$teacherId'
    | '/teachers/create'
    | '/attendance'
    | '/books'
    | '/branches'
    | '/dashboard'
    | '/institutions'
    | '/libraries'
    | '/members'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/seats'
    | '/settings'
    | '/students'
    | '/subscriptions'
    | '/support'
    | '/teachers'
    | '/roles'
    | '/users'
    | '/institutions/$institutionId/branches/$branchId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/register'
    | '/reset-password'
    | '/unauthorized'
    | '/verify-otp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/_admin'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/seats'
    | '/_authenticated/settings'
    | '/onboarding/branch'
    | '/onboarding/institution'
    | '/onboarding/library'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/attendance/calendar'
    | '/_authenticated/attendance/live'
    | '/_authenticated/attendance/scanner'
    | '/_authenticated/attendance/shifts'
    | '/_authenticated/branches/$branchId'
    | '/_authenticated/branches/create'
    | '/_authenticated/dashboard/activity'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/attendance'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/occupancy'
    | '/_authenticated/dashboard/revenue'
    | '/_authenticated/dashboard/subscriptions'
    | '/_authenticated/institutions/$institutionId'
    | '/_authenticated/institutions/create'
    | '/_authenticated/libraries/$libraryId'
    | '/_authenticated/libraries/create'
    | '/_authenticated/members/$memberId'
    | '/_authenticated/members/create'
    | '/_authenticated/seats/heatmap'
    | '/_authenticated/seats/layout'
    | '/_authenticated/seats/monitoring'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/audit'
    | '/_authenticated/settings/branding'
    | '/_authenticated/settings/institution'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/theme'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/students/create'
    | '/_authenticated/support/status'
    | '/_authenticated/teachers/$teacherId'
    | '/_authenticated/teachers/create'
    | '/_authenticated/attendance/'
    | '/_authenticated/books/'
    | '/_authenticated/branches/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/institutions/'
    | '/_authenticated/libraries/'
    | '/_authenticated/members/'
    | '/_authenticated/notifications/'
    | '/_authenticated/payments/'
    | '/_authenticated/reports/'
    | '/_authenticated/seats/'
    | '/_authenticated/settings/'
    | '/_authenticated/students/'
    | '/_authenticated/subscriptions/'
    | '/_authenticated/support/'
    | '/_authenticated/teachers/'
    | '/_authenticated/_admin/roles/'
    | '/_authenticated/_admin/users/'
    | '/_authenticated/institutions/$institutionId/branches/$branchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  OnboardingBranchRoute: typeof OnboardingBranchRoute
  OnboardingInstitutionRoute: typeof OnboardingInstitutionRoute
  OnboardingLibraryRoute: typeof OnboardingLibraryRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/library': {
      id: '/onboarding/library'
      path: '/onboarding/library'
      fullPath: '/onboarding/library'
      preLoaderRoute: typeof OnboardingLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/institution': {
      id: '/onboarding/institution'
      path: '/onboarding/institution'
      fullPath: '/onboarding/institution'
      preLoaderRoute: typeof OnboardingInstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/branch': {
      id: '/onboarding/branch'
      path: '/onboarding/branch'
      fullPath: '/onboarding/branch'
      preLoaderRoute: typeof OnboardingBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seats': {
      id: '/_authenticated/seats'
      path: '/seats'
      fullPath: '/seats'
      preLoaderRoute: typeof AuthenticatedSeatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/': {
      id: '/_authenticated/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthenticatedSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscriptions/': {
      id: '/_authenticated/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof AuthenticatedSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/seats/': {
      id: '/_authenticated/seats/'
      path: '/'
      fullPath: '/seats/'
      preLoaderRoute: typeof AuthenticatedSeatsIndexRouteImport
      parentRoute: typeof AuthenticatedSeatsRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/libraries/': {
      id: '/_authenticated/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof AuthenticatedLibrariesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/institutions/': {
      id: '/_authenticated/institutions/'
      path: '/institutions'
      fullPath: '/institutions/'
      preLoaderRoute: typeof AuthenticatedInstitutionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/branches/': {
      id: '/_authenticated/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AuthenticatedBranchesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/books/': {
      id: '/_authenticated/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AuthenticatedBooksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/teachers/create': {
      id: '/_authenticated/teachers/create'
      path: '/teachers/create'
      fullPath: '/teachers/create'
      preLoaderRoute: typeof AuthenticatedTeachersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teachers/$teacherId': {
      id: '/_authenticated/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof AuthenticatedTeachersTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/status': {
      id: '/_authenticated/support/status'
      path: '/support/status'
      fullPath: '/support/status'
      preLoaderRoute: typeof AuthenticatedSupportStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/create': {
      id: '/_authenticated/students/create'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof AuthenticatedStudentsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/theme': {
      id: '/_authenticated/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof AuthenticatedSettingsThemeRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/institution': {
      id: '/_authenticated/settings/institution'
      path: '/institution'
      fullPath: '/settings/institution'
      preLoaderRoute: typeof AuthenticatedSettingsInstitutionRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/branding': {
      id: '/_authenticated/settings/branding'
      path: '/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AuthenticatedSettingsBrandingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/audit': {
      id: '/_authenticated/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AuthenticatedSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/seats/monitoring': {
      id: '/_authenticated/seats/monitoring'
      path: '/monitoring'
      fullPath: '/seats/monitoring'
      preLoaderRoute: typeof AuthenticatedSeatsMonitoringRouteImport
      parentRoute: typeof AuthenticatedSeatsRoute
    }
    '/_authenticated/seats/layout': {
      id: '/_authenticated/seats/layout'
      path: '/layout'
      fullPath: '/seats/layout'
      preLoaderRoute: typeof AuthenticatedSeatsLayoutRouteImport
      parentRoute: typeof AuthenticatedSeatsRoute
    }
    '/_authenticated/seats/heatmap': {
      id: '/_authenticated/seats/heatmap'
      path: '/heatmap'
      fullPath: '/seats/heatmap'
      preLoaderRoute: typeof AuthenticatedSeatsHeatmapRouteImport
      parentRoute: typeof AuthenticatedSeatsRoute
    }
    '/_authenticated/members/create': {
      id: '/_authenticated/members/create'
      path: '/members/create'
      fullPath: '/members/create'
      preLoaderRoute: typeof AuthenticatedMembersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members/$memberId': {
      id: '/_authenticated/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/libraries/create': {
      id: '/_authenticated/libraries/create'
      path: '/libraries/create'
      fullPath: '/libraries/create'
      preLoaderRoute: typeof AuthenticatedLibrariesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/libraries/$libraryId': {
      id: '/_authenticated/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/institutions/create': {
      id: '/_authenticated/institutions/create'
      path: '/institutions/create'
      fullPath: '/institutions/create'
      preLoaderRoute: typeof AuthenticatedInstitutionsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/institutions/$institutionId': {
      id: '/_authenticated/institutions/$institutionId'
      path: '/institutions/$institutionId'
      fullPath: '/institutions/$institutionId'
      preLoaderRoute: typeof AuthenticatedInstitutionsInstitutionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/subscriptions': {
      id: '/_authenticated/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof AuthenticatedDashboardSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/revenue': {
      id: '/_authenticated/dashboard/revenue'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof AuthenticatedDashboardRevenueRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/occupancy': {
      id: '/_authenticated/dashboard/occupancy'
      path: '/occupancy'
      fullPath: '/dashboard/occupancy'
      preLoaderRoute: typeof AuthenticatedDashboardOccupancyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/attendance': {
      id: '/_authenticated/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof AuthenticatedDashboardAttendanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/activity': {
      id: '/_authenticated/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof AuthenticatedDashboardActivityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/branches/create': {
      id: '/_authenticated/branches/create'
      path: '/branches/create'
      fullPath: '/branches/create'
      preLoaderRoute: typeof AuthenticatedBranchesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branches/$branchId': {
      id: '/_authenticated/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof AuthenticatedBranchesBranchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/shifts': {
      id: '/_authenticated/attendance/shifts'
      path: '/shifts'
      fullPath: '/attendance/shifts'
      preLoaderRoute: typeof AuthenticatedAttendanceShiftsRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/scanner': {
      id: '/_authenticated/attendance/scanner'
      path: '/scanner'
      fullPath: '/attendance/scanner'
      preLoaderRoute: typeof AuthenticatedAttendanceScannerRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/live': {
      id: '/_authenticated/attendance/live'
      path: '/live'
      fullPath: '/attendance/live'
      preLoaderRoute: typeof AuthenticatedAttendanceLiveRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/calendar': {
      id: '/_authenticated/attendance/calendar'
      path: '/calendar'
      fullPath: '/attendance/calendar'
      preLoaderRoute: typeof AuthenticatedAttendanceCalendarRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/users/': {
      id: '/_authenticated/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/roles/': {
      id: '/_authenticated/_admin/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/institutions/$institutionId/branches/$branchId': {
      id: '/_authenticated/institutions/$institutionId/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/institutions/$institutionId/branches/$branchId'
      preLoaderRoute: typeof AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRouteImport
      parentRoute: typeof AuthenticatedInstitutionsInstitutionIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAttendanceRouteChildren {
  AuthenticatedAttendanceCalendarRoute: typeof AuthenticatedAttendanceCalendarRoute
  AuthenticatedAttendanceLiveRoute: typeof AuthenticatedAttendanceLiveRoute
  AuthenticatedAttendanceScannerRoute: typeof AuthenticatedAttendanceScannerRoute
  AuthenticatedAttendanceShiftsRoute: typeof AuthenticatedAttendanceShiftsRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
}

const AuthenticatedAttendanceRouteChildren: AuthenticatedAttendanceRouteChildren =
  {
    AuthenticatedAttendanceCalendarRoute: AuthenticatedAttendanceCalendarRoute,
    AuthenticatedAttendanceLiveRoute: AuthenticatedAttendanceLiveRoute,
    AuthenticatedAttendanceScannerRoute: AuthenticatedAttendanceScannerRoute,
    AuthenticatedAttendanceShiftsRoute: AuthenticatedAttendanceShiftsRoute,
    AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  }

const AuthenticatedAttendanceRouteWithChildren =
  AuthenticatedAttendanceRoute._addFileChildren(
    AuthenticatedAttendanceRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardActivityRoute: typeof AuthenticatedDashboardActivityRoute
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardAttendanceRoute: typeof AuthenticatedDashboardAttendanceRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardOccupancyRoute: typeof AuthenticatedDashboardOccupancyRoute
  AuthenticatedDashboardRevenueRoute: typeof AuthenticatedDashboardRevenueRoute
  AuthenticatedDashboardSubscriptionsRoute: typeof AuthenticatedDashboardSubscriptionsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardActivityRoute: AuthenticatedDashboardActivityRoute,
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardAttendanceRoute:
      AuthenticatedDashboardAttendanceRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardOccupancyRoute: AuthenticatedDashboardOccupancyRoute,
    AuthenticatedDashboardRevenueRoute: AuthenticatedDashboardRevenueRoute,
    AuthenticatedDashboardSubscriptionsRoute:
      AuthenticatedDashboardSubscriptionsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedSeatsRouteChildren {
  AuthenticatedSeatsHeatmapRoute: typeof AuthenticatedSeatsHeatmapRoute
  AuthenticatedSeatsLayoutRoute: typeof AuthenticatedSeatsLayoutRoute
  AuthenticatedSeatsMonitoringRoute: typeof AuthenticatedSeatsMonitoringRoute
  AuthenticatedSeatsIndexRoute: typeof AuthenticatedSeatsIndexRoute
}

const AuthenticatedSeatsRouteChildren: AuthenticatedSeatsRouteChildren = {
  AuthenticatedSeatsHeatmapRoute: AuthenticatedSeatsHeatmapRoute,
  AuthenticatedSeatsLayoutRoute: AuthenticatedSeatsLayoutRoute,
  AuthenticatedSeatsMonitoringRoute: AuthenticatedSeatsMonitoringRoute,
  AuthenticatedSeatsIndexRoute: AuthenticatedSeatsIndexRoute,
}

const AuthenticatedSeatsRouteWithChildren =
  AuthenticatedSeatsRoute._addFileChildren(AuthenticatedSeatsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAuditRoute: typeof AuthenticatedSettingsAuditRoute
  AuthenticatedSettingsBrandingRoute: typeof AuthenticatedSettingsBrandingRoute
  AuthenticatedSettingsInstitutionRoute: typeof AuthenticatedSettingsInstitutionRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsThemeRoute: typeof AuthenticatedSettingsThemeRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsAuditRoute: AuthenticatedSettingsAuditRoute,
  AuthenticatedSettingsBrandingRoute: AuthenticatedSettingsBrandingRoute,
  AuthenticatedSettingsInstitutionRoute: AuthenticatedSettingsInstitutionRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsThemeRoute: AuthenticatedSettingsThemeRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedInstitutionsInstitutionIdRouteChildren {
  AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRoute: typeof AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRoute
}

const AuthenticatedInstitutionsInstitutionIdRouteChildren: AuthenticatedInstitutionsInstitutionIdRouteChildren =
  {
    AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRoute:
      AuthenticatedInstitutionsInstitutionIdBranchesBranchIdRoute,
  }

const AuthenticatedInstitutionsInstitutionIdRouteWithChildren =
  AuthenticatedInstitutionsInstitutionIdRoute._addFileChildren(
    AuthenticatedInstitutionsInstitutionIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedSeatsRoute: typeof AuthenticatedSeatsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedBranchesBranchIdRoute: typeof AuthenticatedBranchesBranchIdRoute
  AuthenticatedBranchesCreateRoute: typeof AuthenticatedBranchesCreateRoute
  AuthenticatedInstitutionsInstitutionIdRoute: typeof AuthenticatedInstitutionsInstitutionIdRouteWithChildren
  AuthenticatedInstitutionsCreateRoute: typeof AuthenticatedInstitutionsCreateRoute
  AuthenticatedLibrariesLibraryIdRoute: typeof AuthenticatedLibrariesLibraryIdRoute
  AuthenticatedLibrariesCreateRoute: typeof AuthenticatedLibrariesCreateRoute
  AuthenticatedMembersMemberIdRoute: typeof AuthenticatedMembersMemberIdRoute
  AuthenticatedMembersCreateRoute: typeof AuthenticatedMembersCreateRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedStudentsCreateRoute: typeof AuthenticatedStudentsCreateRoute
  AuthenticatedSupportStatusRoute: typeof AuthenticatedSupportStatusRoute
  AuthenticatedTeachersTeacherIdRoute: typeof AuthenticatedTeachersTeacherIdRoute
  AuthenticatedTeachersCreateRoute: typeof AuthenticatedTeachersCreateRoute
  AuthenticatedBooksIndexRoute: typeof AuthenticatedBooksIndexRoute
  AuthenticatedBranchesIndexRoute: typeof AuthenticatedBranchesIndexRoute
  AuthenticatedInstitutionsIndexRoute: typeof AuthenticatedInstitutionsIndexRoute
  AuthenticatedLibrariesIndexRoute: typeof AuthenticatedLibrariesIndexRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedSubscriptionsIndexRoute: typeof AuthenticatedSubscriptionsIndexRoute
  AuthenticatedSupportIndexRoute: typeof AuthenticatedSupportIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedSeatsRoute: AuthenticatedSeatsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedBranchesBranchIdRoute: AuthenticatedBranchesBranchIdRoute,
  AuthenticatedBranchesCreateRoute: AuthenticatedBranchesCreateRoute,
  AuthenticatedInstitutionsInstitutionIdRoute:
    AuthenticatedInstitutionsInstitutionIdRouteWithChildren,
  AuthenticatedInstitutionsCreateRoute: AuthenticatedInstitutionsCreateRoute,
  AuthenticatedLibrariesLibraryIdRoute: AuthenticatedLibrariesLibraryIdRoute,
  AuthenticatedLibrariesCreateRoute: AuthenticatedLibrariesCreateRoute,
  AuthenticatedMembersMemberIdRoute: AuthenticatedMembersMemberIdRoute,
  AuthenticatedMembersCreateRoute: AuthenticatedMembersCreateRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedStudentsCreateRoute: AuthenticatedStudentsCreateRoute,
  AuthenticatedSupportStatusRoute: AuthenticatedSupportStatusRoute,
  AuthenticatedTeachersTeacherIdRoute: AuthenticatedTeachersTeacherIdRoute,
  AuthenticatedTeachersCreateRoute: AuthenticatedTeachersCreateRoute,
  AuthenticatedBooksIndexRoute: AuthenticatedBooksIndexRoute,
  AuthenticatedBranchesIndexRoute: AuthenticatedBranchesIndexRoute,
  AuthenticatedInstitutionsIndexRoute: AuthenticatedInstitutionsIndexRoute,
  AuthenticatedLibrariesIndexRoute: AuthenticatedLibrariesIndexRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedSubscriptionsIndexRoute: AuthenticatedSubscriptionsIndexRoute,
  AuthenticatedSupportIndexRoute: AuthenticatedSupportIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  OnboardingBranchRoute: OnboardingBranchRoute,
  OnboardingInstitutionRoute: OnboardingInstitutionRoute,
  OnboardingLibraryRoute: OnboardingLibraryRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
