import { LexoraTeamMember } from '../app/core/models/lexora-team-member.model';

export const environment = {
  production: true,
  environmentName: 'uat',
  baseUrl: '',
  apiUrl: 'https://uat-api.lexora.app/api/v1',
  siteUrl: 'https://uniappx.in',
  mockApi: false,
  appName: 'Lexora',
  appVersion: 'v1.0.0-beta',
  appEdition: 'UAT Release',
  email: '',
  password: '',
  TOKEN_KEY: 'access_token',
  REFRESH_TOKEN_KEY: 'refresh_token',
  ACCESS_TOKEN_EXPIRES_KEY: 'access_token_expires',
  REFRESH_TOKEN_EXPIRES_KEY: 'refresh_token_expires',
  USER_KEY: 'user',
  TENANT_KEY: 'tenant',
  STORAGE_KEY: 'slms_auth',
  MOCK_OTP: '',
  lexoraTeam: [
    {
      name: 'Yogesh Yadav',
      role: 'Founder & Product Lead',
      bio: 'Leads Lexora product vision for multi-branch library institutions.',
      email: 'yogesh@lexora.app',
      linkedIn: 'https://www.linkedin.com/',
    },
    {
      name: 'Platform Engineering',
      role: 'Backend & Multi-Tenant Architecture',
      bio: 'Builds secure APIs, tenant isolation, and institution workflows.',
      email: 'engineering@lexora.app',
    },
    {
      name: 'Experience Design',
      role: 'UI/UX & Frontend',
      bio: 'Crafts admin dashboards, member flows, and landing experiences.',
      email: 'design@lexora.app',
    },
    {
      name: 'Customer Success',
      role: 'Onboarding & Support',
      bio: 'Helps institutions launch branches, libraries, and member operations.',
      email: 'support@lexora.app',
    },
  ] as LexoraTeamMember[],
  superAdminContact: {
    email: 'er.yogeshrao@gmail.com',
    phone: '+91 9992823909',
    secondaryPhone: '+91 9468118737',
    whatsApp: '+91 9992823909',
    whatsAppUrl: 'https://wa.me/919992823909',
    availability: 'Instant Verification & Activation Support (9:00 AM - 9:00 PM IST)',
  },
};
